### ISSUE TITLE
Error en el listener de kafka si ya hay datos dentro ...

### ISSUE THREAD

**Issue by sankosk** [Arquisoft/InciDashboard_e1b#31]
... cuando se carga la aplicación

![deepinscreenshot_seleccionar area_20180501191840](https://user-images.githubusercontent.com/3002802/39483985-7e99ef9c-4d74-11e8-8fad-8982307e7b3d.png)

**Comment by Fireruner** [comment]
Okay. Asigno a Sergio que fue el que hizo toda esa parte, y si necesita ayuda que me comente y le echo un cable

**Comment by sergiofdezfernandez** [comment]
ya esta solucionado.
