### ISSUE TITLE
Error: Duplicación de incidencias ... 

### ISSUE THREAD

**Issue by sankosk** [Arquisoft/InciDashboard_e1b#32]
... el listener duplica la incidencia y le añade campos de más: vease el campo "operario" y además el campo "expiration" que debería de llamarse "expireAt", por lo que aparte de duplicarse, no se muestra la fecha de "caducidad" en el panel

{
    "_id": {
        "$oid": "5ae89fb085d6f516b86f3b7d"
    },
    "_class": "com.e1b.entities.Incidence",
    "operario": {
        "_id": null
    },
    "name": "AAAAA",
    "description": "AAAA",
    "location": "25,25",
    "tags": [
        "dwada",
        "dawdaw"
    ],
    "additionalInformation": "www.google.es",
    "properties": {
        "p0": "v0",
        "p1": "v1"
    },
    "state": "Abierta",
    "notification": "Si",
    "expiration": "2018-15-02",
    "assignedTo": "entidad2"
}

**Comment by Fireruner** [comment]
Okay, le echo un ojo

**Comment by sergiofdezfernandez** [comment]
Ya esta arreglado
